version: '3'
services:
 database:
   image: 'mongo:latest'
   container_name: 'mongodb'
   environment:
     - 'MONGO_DATA_DIR=/data/db'
   volumes:
     - './database:/data/db'
   command: 'mongod --smallfiles'
   ports: 
     - '27017:27017'